### ISSUE TITLE
Refactor Hilbert to be More Memory Efficient

### ISSUE THREAD

**Issue by pmyers16** [mne-tools/mne-hfo#33]
#### Describe the problem
The current implementation has an internal state that stores a (n_channels x n_times x n_bands) matrix, which ends up eating up 30+GB of RAM if using linear band method and 20+ GB of RAM if using the log band method for  a 30 minute clip sampled at 2000 Hz.

#### Describe your solution
Default to processing each channels data sequentially, parallelizing over bands, and merging in post-processing when array sizes are more manageable. 

#### Describe possible alternatives
The alternative is to keep it as it is since it runs, just inefficiently

**Comment by adam2392** [comment]
This LGTM. ping me when you want me to look at PR.
