### ISSUE TITLE
Hilbert detector error message

### ISSUE THREAD

**Issue by fishbacp** [mne-tools/mne-hfo#42]
I'm having a problem with the Hilbert detector. If raw is my mne-raw structure and fs is my sampling frequency,

detector=HilbertDetector(sfreq=fs, l_freq=80,h_freq=fs/2)
detector.fit(raw)
hfo_event_df = detector.hfo_event_df

produces the error message

```
Traceback (most recent call last):
  File "/Users/fishbacp/Desktop/Python_May_2021/Idle_script.py", line 20, in <module>
    detector.fit(raw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mne_hfo/detect.py", line 207, in fit
    n_chs, n_times = X.shape
AttributeError: 'RawEDF' object has no attribute 'shape'
```

**Comment by adam2392** [comment]
Hi @fishbacp can you try using the master branch version on GH? I think that might be from an error in v0.1 of mne-hfo. 

We will try to officially release v0.2 sometime this upcoming month. In the meantime, directly installing `mne-hfo` from master branch should work. Lmk if it doesn't.

**Comment by fishbacp** [comment]
@adam2392:

Still having the same problem. Downloaded mne-hfo-master.zip file directly and placed in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages. 

Then unzipped

At terminal, typed

cd /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/

python3 setup.py install

My knowledge of installing modules using means beyond PyPi is quite limited. Perhaps I missed something basic in this process?

**Comment by adam2392** [comment]
Lmk if this works: https://mne.tools/mne-hfo/dev/install.html

pip install --user -U https://api.github.com/repos/adam2392/mne-hfo/zipball/master

**Comment by adam2392** [comment]
I also just released v0.2, which is now on pipy, so `pip install --upgrade mne-hfo` should work as well.

Please lmk if this solves your issue?

**Comment by fishbacp** [comment]
Still having the problem after trying v0.2. Here's what I've tried, once with a 10-minute file having sampling rate 200 and then with a two-hour file having sampling rate 1000:

```
import mne
from mne_hfo import HilbertDetector
raw = mne.io.read_raw_edf('filename.edf', preload=True)
fs=raw.info['sfreq']
detector=HilbertDetector(sfreq=fs, l_freq=80,h_freq=.9*fs/2)
detector.fit(raw)
```
In both cases, the error message came back

```
Traceback (most recent call last):
  File "/Users/fishbacp/Desktop/Python_May_2021/Idle_script.py", line 12, in <module>
    detector.fit(raw)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mne_hfo/detect.py", line 207, in fit
    n_chs, n_times = X.shape
AttributeError: 'RawEDF' object has no attribute 'shape'

```

I'm using Python 3.9 on a Mac running Big Sur if that makes any difference. I apologize if I'm overlooking something obvious. 

Thanks

**Comment by adam2392** [comment]
It seems like you're still probably on the wrong version because the code at: https://github.com/mne-tools/mne-hfo/blob/77faf25a73001f87b167b26ae1a1cf885d54d9a5/mne_hfo/detect.py#L207-L211 

doesn't match the line 207 you're seeing.

**Comment by fishbacp** [comment]
Got it working. Thanks!
